services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    network_mode: bridge
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/flaae/.local/docker/portainer/data:/data
    labels:
      - homepage.group=Management
      - homepage.name=Portainer
      - homepage.icon=portainer
      - homepage.description=Container Management
    restart: always
