services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    hostname: dockge
    network_mode: bridge
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/flaae/docker/dockge/data:/app/data
      # change container to reflect same structure for stacks?
      - /home/flaae/docker/dockge/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    labels:
      - homepage.group=Management
      - homepage.name=Dockge
      - homepage.icon=uptime-kuma  # theres no dockge icon yet
      - homepage.href=https://dockge.news13.nl
      - homepage.description=Docker Compose Manager
    restart: always